### PR TITLE
updates for clarification

### PR DESCRIPTION
**Pull request by TeaganKing**

### CODE REVIEW

**Review by wwieder — APPROVED** [review]
Thanks Teagan!

**Comment by TeaganKing** [comment]
Thanks. I'm still looking at the additional tutorials, but these ones are good to go. I emailed you and @danicalombardozzi  and Gordon, as well with some additional details and suggestions for changes, but if other folks are reviewing shortly we could just merge this in. If not, it may be easier on your end to make any changes all at once, but it shouldn't be an issue to merge this now.

**Comment by TeaganKing** [comment]
Great! In that case, this is ready to merge. I emailed the whole group to make sure we're all on the same page, as well.

**Comment by wwieder** [comment]
Thanks @TeaganKing.  @danicalombardozzi do you want to start from the head of this branch to review the tutorial materials we have for the NEON workshop?

**Pull request merged**
